apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: banking-app
          image: 923093694371.dkr.ecr.ap-south-1.amazonaws.com/banking-app:4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
